/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */



#include "core_cm3.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32_F103C6.h"
#include "STM32F103C6_GPIO_DRIVERS.h"
#include "LCD_ME.h"
#include "EXTI_DRIVER.h"
#include "scheduler.h"

Task_ref Task1,Task2,Task3,Task4;
unsigned char Task1LED,Task2LED,Task3LED,Task4LED;


void task1()
{
	static int count=0;
	while(1)

	{
		Task1LED ^=1;
		// code of task 1
		count++;
				if(count==30)
				{
				  MYRTOS_ActivateTask(&Task4);
				  count=0;
				}

		MYRTOS_TaskWait(100,&Task1);
	}
}

void task2()

{
	while(1)
	{
		Task2LED ^=1;
		// code of task 2

		MYRTOS_TaskWait(300,&Task2);

	}
}

void task3()
{
	while(1)
	{
		Task3LED ^=1;
		// code of task 3
		MYRTOS_TaskWait(500,&Task3);

	}
}

void task4()
{
	static int count=0;
	while(1)

	{
		Task4LED ^=1;
		// code of task 1

		MYRTOS_TaskWait(1000,&Task4);

	}
}

unsigned int state_error;

int main(void)

{

	MYRTOS_ErrorID error;
	//HW_init (initialize clockTree, RestController)

	HW_init();

	state_error	 = MYRTOS_init();

	if (state_error != NOERROR)
		while (1);


	Task1.Stack_Size=1024;
	Task1.P_TaskEntry=task1;
	Task1.priority=3;
	strcpy(Task1.TaskName,"task_1");

	Task2.Stack_Size=1024;
	Task2.P_TaskEntry=task2;
	Task2.priority=3;
	strcpy(Task2.TaskName,"task_2");

	Task3.Stack_Size=1024;
	Task3.P_TaskEntry=task3;
	Task3.priority=3;
	strcpy(Task3.TaskName,"task_3");

	Task4.Stack_Size=1024;
	Task4.P_TaskEntry=task4;
	Task4.priority=1;
	strcpy(Task4.TaskName,"task_4");

	error+= MYRTOS_CreatTask(&Task1);
	error+= MYRTOS_CreatTask(&Task2);
	error+= MYRTOS_CreatTask(&Task3);
	error+= MYRTOS_CreatTask(&Task4);

	// mean that will arrange in queue table and get it ready
	MYRTOS_ActivateTask(&Task1);
	MYRTOS_ActivateTask(&Task2);
	MYRTOS_ActivateTask(&Task3);
	MYRTOS_ActivateTask(&Task4);


	MYRTOS_STARTOS(); // there is an activation for idle Task inside this function and make the current task is idle task also

	while(1)
	{

	}


}









